### ISSUE TITLE
OPC UA Modelling Features

### ISSUE THREAD

**Issue by jjdm24** [model-UA/uml-to-opcua#13]
Hi,
Please help me, and thank you in advance for your answers.

I would like to install the plugin OPC UA to allow me to transform a diagram UML to OPC UA, unfortunately I am unable to install the plugin OPC UA by trying to add the address : https://model-ua.auto.tuwien.ac.at/updates/releases

I keep having the error messages below 👍 
Unable to read repository at https://model-ua.auto.tuwien.ac.at/updates/releases/content.xml.
Unable to read repository at https://model-ua.auto.tuwien.ac.at/updates/releases/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

![image](https://user-images.githubusercontent.com/81247112/112381806-510de380-8ceb-11eb-8853-b94c2f771cd8.png)

**Comment by thomasfruehwirth** [comment]
Hi,

Thanks for your request. We encountered a problem regarding the certificate of the website. Should be fixed now. Can you please try again?

**Comment by jjdm24** [comment]
Hi Thomas,

Thank you so much for your help, it works now, and I don't have the problem any more.

Best Regards,

Julien
